### ISSUE TITLE
construct problem

### ISSUE THREAD

**Issue by joyhope** [go-tango/wego#1] opened 2017-04-03 04:42 UTC
qiniu changed repository:

package github.com/qiniu/api/conf: cannot find package "github.com/qiniu/api/conf"

api.v7 or api.v6.

**Comment by lunny** [comment] 2017-04-03 06:11
The latest version has used govendor to manage dependency. If your Go version >= 1.5, you will not encouter the issue.

**Comment by joyhope** [comment] 2017-04-11 04:56
i use go1.8

D:\GoPrj\src\github.com\go-tango\wego>go build
setting\conf.go:39:2: cannot find package "github.com/qiniu/api/conf" in any of:
        d:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu\api\conf (vendor tree)
        e:\Go\src\github.com\qiniu\api\conf (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\conf (from $GOPATH)
modules\utils\qiniu.go:4:2: cannot find package "github.com/qiniu/api/fop" in any of:
        d:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu\api\fop (vendor tree)
        e:\Go\src\github.com\qiniu\api\fop (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\fop (from $GOPATH)
modules\auth\auth.go:37:2: cannot find package "github.com/qiniu/api/io" in any of:
        d:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu\api\io (vendor tree)
        e:\Go\src\github.com\qiniu\api\io (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\io (from $GOPATH)
modules\utils\qiniu.go:5:2: cannot find package "github.com/qiniu/api/rs" in any of:
        d:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu\api\rs (vendor tree)
        e:\Go\src\github.com\qiniu\api\rs (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\rs (from $GOPATH)

**Comment by lunny** [comment] 2017-04-11 05:01
@joyhope which git tag version of your wego?

**Comment by joyhope** [comment] 2017-04-11 08:14
master

**Comment by joyhope** [comment] 2017-04-11 08:20
I just process as the readme, step by step, but without success.  I tried both windows and linux platform, none of them was success constructed. 

Hope the construct problem could be solved.  thanks.

**Comment by lunny** [comment] 2017-04-11 11:57
please help to confirm that `d:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu\api\fop` dir is exist?

**Comment by joyhope** [comment] 2017-04-12 01:56
go get github.com/go-tango/wego
package github.com/qiniu/api/conf: cannot find package "github.com/qiniu/api/conf" in any of:
        e:\Go\src\github.com\qiniu\api\conf (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\conf (from $GOPATH)
package github.com/qiniu/api/fop: cannot find package "github.com/qiniu/api/fop" in any of:
        e:\Go\src\github.com\qiniu\api\fop (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\fop (from $GOPATH)
package github.com/qiniu/api/rs: cannot find package "github.com/qiniu/api/rs" in any of:
        e:\Go\src\github.com\qiniu\api\rs (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\rs (from $GOPATH)
package github.com/qiniu/api/io: cannot find package "github.com/qiniu/api/io" in any of:
        e:\Go\src\github.com\qiniu\api\io (from $GOROOT)
        d:\GoPrj\src\github.com\qiniu\api\io (from $GOPATH)

There is no fop:   I could got get it.
D:\GoPrj\src\github.com\go-tango\wego\vendor\github.com\qiniu>tree
卷 Data 的文件夹 PATH 列表
卷序列号为 0000005B 1624:ACA8
D:.
├─bytes
│  └─seekable
└─rpc

govendor sync
D:\GoPrj\src\github.com\go-tango\wego>govendor sync
# cd d:\GoPrj\.cache\govendor\github.com\go-xweb\xweb; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
# cd d:\GoPrj\.cache\govendor\github.com\qiniu\api; git fetch
Error: Remotes failed for:
        Failed for "github.com/go-xweb/xweb/validation" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/auth/digest" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/conf" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/fop" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/io" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/rs" (failed to download repo): exit status 128
        Failed for "github.com/qiniu/api/url" (failed to download repo): exit status 128

**Comment by joyhope** [comment] 2017-04-12 01:58
I make all these in both windows and Linux.  All failure. I think it is because the remote repo is changed, the project has not syn with the latest repository.  I am curiosity for the forum looks like, but unable to create a work version.

**Comment by lunny** [comment] 2017-04-12 09:21
I cannot reproduce this.

**Comment by joyhope** [comment] 2017-04-14 03:34
All these problem repo: 
https://github.com/qiniu/api/url
https://github.com/qiniu/api/fop

are both return 404.  Why you could not reproduce it? 

Whether you have a special account could get this repository, but normal develop could not.

**Comment by lunny** [comment] 2017-11-08 02:56
fixed by 775281b

**Closed by lunny** 2017-11-08 02:56 UTC
Labels: question
